<?php
session_start();

// منع إعادة التثبيت إذا كان قد تم بالفعل
if (file_exists(__DIR__ . '/../install.lock')) {
    die("خطأ: المشروع تم تثبيته بالفعل. يرجى حذف ملف 'install.lock' يدوياً لإعادة التثبيت.");
}


// --- منطق معالجة الفورم ---
$error = null;
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['form_step'])) {
    if ((int)$_POST['form_step'] === 2) {
        // معالجة فورم إنشاء حساب المدير
        $username = trim($_POST['username'] ?? '');
        $password = trim($_POST['password'] ?? '');

        if (strlen($username) > 2 && strlen($password) > 5) {
            $_SESSION['install_admin_user'] = [
                'username' => $username,
                'password_hash' => password_hash($password, PASSWORD_DEFAULT),
            ];
            header('Location: ?step=3');
            exit;
        } else {
            $error = "اسم المستخدم يجب أن يكون أطول من حرفين، وكلمة المرور أطول من 5 أحرف.";
        }
    } elseif ((int)$_POST['form_step'] === 3) {
        // --- إنشاء ملف الإعدادات ---
        $config_content = "<?php\n\n";
        $config_content .= "// Generated by installer on " . date('Y-m-d H:i:s') . " --\n\n";

        // Sanitize and prepare data
        $db_host = trim($_POST['db_host']);
        $db_user = trim($_POST['db_user']);
        $db_pass = trim($_POST['db_pass']);
        $db_name = trim($_POST['db_name']);

        $source_dirs = array_filter(array_map('trim', explode("\n", $_POST['source_dirs'])));
        $source_dirs_str = "['" . implode("', '", array_map('addslashes', $source_dirs)) . "']";

        $exclude_patterns = array_filter(array_map('trim', explode("\n", $_POST['exclude_patterns'])));
        $exclude_patterns_str = "['" . implode("', '", array_map('addslashes', $exclude_patterns)) . "']";

        $keep_days = (int)$_POST['keep_days'];
        $delete_old = isset($_POST['delete_old']) ? 'true' : 'false';

        $ftp_enabled = isset($_POST['ftp_enabled']) ? 'true' : 'false';
        $ftp_host = trim($_POST['ftp_host']);
        $ftp_user = trim($_POST['ftp_user']);
        $ftp_pass = trim($_POST['ftp_pass']);
        $ftp_dir = trim($_POST['ftp_dir']);

        // Build config content
        $config_content .= "// Database Settings\n";
        $config_content .= "define('DB_HOST', '" . addslashes($db_host) . "');\n";
        $config_content .= "define('DB_USER', '" . addslashes($db_user) . "');\n";
        $config_content .= "define('DB_PASS', '" . addslashes($db_pass) . "');\n";
        $config_content .= "define('DB_NAME', '" . addslashes($db_name) . "');\n\n";

        $config_content .= "// File Backup Settings\n";
        $config_content .= "define('SOURCE_DIRECTORIES', " . $source_dirs_str . ");\n";
        $config_content .= "define('EXCLUDE_PATTERNS', " . $exclude_patterns_str . ");\n\n";

        $config_content .= "// General Settings\n";
        $config_content .= "define('BACKUP_DIR', __DIR__ . '/../backups');\n";
        $config_content .= "define('LOG_FILE', __DIR__ . '/../logs/backup.log');\n";
        $config_content .= "define('DELETE_OLD_BACKUPS', " . $delete_old . ");\n";
        $config_content .= "define('KEEP_BACKUPS_FOR_DAYS', " . $keep_days . ");\n\n";

        $config_content .= "// FTP Settings\n";
        $config_content .= "define('FTP_ENABLED', " . $ftp_enabled . ");\n";
        $config_content .= "define('FTP_HOST', '" . addslashes($ftp_host) . "');\n";
        $config_content .= "define('FTP_USER', '" . addslashes($ftp_user) . "');\n";
        $config_content .= "define('FTP_PASS', '" . addslashes($ftp_pass) . "');\n";
        $config_content .= "define('FTP_DIR', '" . addslashes($ftp_dir) . "');\n";

        if (file_put_contents(__DIR__ . '/../config/config.php', $config_content)) {
            header('Location: ?step=4');
            exit;
        } else {
            $error = "فشل في كتابة ملف الإعدادات. يرجى التحقق من صلاحيات مجلد 'config'.";
            // Stay on step 3 to show the error
            $_GET['step'] = 3;
        }
    }
}


// --- منطق الخطوات ---
$step = isset($_GET['step']) ? (int)$_GET['step'] : 1;

// --- عرض الواجهة ---
?>
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>معالج تثبيت سكربت النسخ الاحتياطي</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.rtl.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <style>
        body { background-color: #f0f2f5; }
        .card { margin-top: 50px; }
        .progress-bar {
            display: flex;
            justify-content: space-between;
            margin-bottom: 30px;
            list-style: none;
            padding-left: 0;
        }
        .progress-bar li {
            flex: 1;
            text-align: center;
            position: relative;
            color: #adb5bd;
        }
        .progress-bar li.active { color: #0d6efd; font-weight: bold; }
        .progress-bar li::before {
            content: '';
            width: 100%;
            height: 2px;
            background-color: #dee2e6;
            position: absolute;
            top: 50%;
            left: -50%;
            z-index: -1;
        }
        .progress-bar li:first-child::before { content: none; }
    </style>
</head>
<body>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card shadow-sm">
                    <div class="card-header text-center bg-white border-0 py-3">
                        <h1 class="h4">معالج تثبيت سكربت النسخ الاحتياطي</h1>
                    </div>
                    <div class="card-body p-4">
                        <ul class="progress-bar">
                            <li class="<?php echo $step >= 1 ? 'active' : '' ?>">المتطلبات</li>
                            <li class="<?php echo $step >= 2 ? 'active' : '' ?>">حساب المدير</li>
                            <li class="<?php echo $step >= 3 ? 'active' : '' ?>">الإعدادات</li>
                            <li class="<?php echo $step >= 4 ? 'active' : '' ?>">إنهاء</li>
                        </ul>

                        <?php if ($step === 1): ?>
                            <h2 class="h5 mb-3">الخطوة 1: التحقق من متطلبات السيرفر</h2>
                            <div id="checks-table">
                                <?php
                                    // This block will be replaced by JS, but is needed for non-JS users
                                    // and initial page load.
                                    require_once 'installer/checks.php';
                                    echo render_checks_table();
                                ?>
                            </div>
                            <div class="text-end mt-4">
                                <button id="recheck-btn" class="btn btn-secondary">إعادة الفحص</button>
                                <a href="?step=2" id="next-btn" class="btn btn-primary disabled">الخطوة التالية &larr;</a>
                            </div>
                        <?php endif; ?>

                        <?php if ($step === 2): ?>
                            <h2 class="h5 mb-3">الخطوة 2: إنشاء حساب المدير</h2>
                            <?php if ($error): ?><div class="alert alert-danger"><?php echo $error; ?></div><?php endif; ?>
                            <form method="POST" action="?step=2">
                                <input type="hidden" name="form_step" value="2">
                                <div class="mb-3">
                                    <label for="username" class="form-label">اسم المستخدم:</label>
                                    <input type="text" id="username" name="username" class="form-control" required>
                                </div>
                                <div class="mb-3">
                                    <label for="password" class="form-label">كلمة المرور:</label>
                                    <input type="password" id="password" name="password" class="form-control" required>
                                </div>
                                <div class="text-end">
                                    <button type="submit" class="btn btn-primary">الخطوة التالية &larr;</button>
                                </div>
                            </form>
                        <?php endif; ?>

                        <?php if ($step === 3): ?>
                             <h2 class="h5 mb-3">الخطوة 3: إعدادات النسخ الاحتياطي</h2>
                            <?php if ($error): ?><div class="alert alert-danger"><?php echo $error; ?></div><?php endif; ?>
                            <form method="POST" action="?step=3" class="row g-3">
                                <input type="hidden" name="form_step" value="3">
                                <div class="col-12"><h5>إعدادات قاعدة البيانات</h5></div>
                                <div class="col-md-6"><label class="form-label">مستضيف DB:</label><input type="text" name="db_host" value="localhost" class="form-control"></div>
                                <div class="col-md-6"><label class="form-label">اسم مستخدم DB:</label><input type="text" name="db_user" value="root" class="form-control"></div>
                                <div class="col-md-6"><label class="form-label">كلمة مرور DB:</label><input type="password" name="db_pass" class="form-control"></div>
                                <div class="col-md-6"><label class="form-label">اسم قاعدة البيانات:</label><input type="text" name="db_name" required class="form-control"></div>

                                <div class="col-12 mt-4"><h5>إعدادات نسخ الملفات</h5></div>
                                <div class="col-12"><label class="form-label">المجلدات المصدر (كل مجلد في سطر):</label><textarea name="source_dirs" rows="3" class="form-control" required>/var/www/html</textarea></div>
                                <div class="col-12"><label class="form-label">ملفات/مجلدات للاستثناء (كل نمط في سطر):</label><textarea name="exclude_patterns" rows="3" class="form-control">node_modules&#10;cache&#10;*.log</textarea></div>

                                <div class="col-12 mt-4"><h5>إعدادات عامة و FTP</h5></div>
                                <div class="col-md-6"><label class="form-label">الاحتفاظ بالنسخ لمدة (أيام):</label><input type="number" name="keep_days" value="7" class="form-control"></div>
                                <div class="col-md-6 d-flex align-items-end"><div class="form-check"><input type="checkbox" name="delete_old" value="1" class="form-check-input" checked><label class="form-check-label">حذف النسخ القديمة</label></div></div>
                                <div class="col-md-6 d-flex align-items-end"><div class="form-check"><input type="checkbox" name="ftp_enabled" value="1" class="form-check-input"><label class="form-check-label">تفعيل FTP</label></div></div>
                                <div class="col-md-6"><label class="form-label">مستضيف FTP:</label><input type="text" name="ftp_host" class="form-control"></div>
                                <div class="col-md-6"><label class="form-label">مستخدم FTP:</label><input type="text" name="ftp_user" class="form-control"></div>
                                <div class="col-md-6"><label class="form-label">كلمة مرور FTP:</label><input type="password" name="ftp_pass" class="form-control"></div>
                                <div class="col-md-12"><label class="form-label">مجلد FTP البعيد:</label><input type="text" name="ftp_dir" value="/backups" class="form-control"></div>

                                <div class="col-12 text-end mt-4">
                                    <button type="submit" class="btn btn-primary">حفظ وإنهاء التثبيت &larr;</button>
                                </div>
                            </form>
                        <?php endif; ?>

                        <?php if ($step === 4): ?>
                            <div class="text-center">
                                <?php
                                    $install_success = false;
                                    try {
                                        if (!isset($_SESSION['install_admin_user'])) { throw new Exception("بيانات المدير غير موجودة في الجلسة."); }
                                        $db_path = __DIR__ . '/../database/users.db';
                                        $pdo = new PDO('sqlite:' . $db_path);
                                        $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
                                        $pdo->exec("CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, username TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL)");
                                        $stmt = $pdo->prepare("INSERT INTO users (username, password_hash) VALUES (?, ?)");
                                        $stmt->execute([$_SESSION['install_admin_user']['username'], $_SESSION['install_admin_user']['password_hash']]);
                                        touch(__DIR__ . '/../install.lock');
                                        session_destroy();
                                        $install_success = true;
                                    } catch (Exception $e) {
                                        echo "<div class='alert alert-danger'>حدث خطأ فادح: " . $e->getMessage() . "</div>";
                                    }
                                ?>
                                <?php if ($install_success): ?>
                                    <i class="bi bi-check-circle-fill text-success" style="font-size: 4rem;"></i>
                                    <h2 class="h5 mt-3">تم التثبيت بنجاح!</h2>
                                    <p class="text-muted">تم إعداد النظام وهو جاهز للاستخدام.</p>
                                    <div class="alert alert-warning"><strong>ملاحظة هامة:</strong> لأسباب أمنية، يرجى حذف ملف `public/install.php` الآن.</div>
                                    <a href="index.php" class="btn btn-primary mt-3">الذهاب إلى صفحة تسجيل الدخول &larr;</a>
                                <?php endif; ?>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const step = <?php echo $step; ?>;

            if (step === 1) {
                const recheckBtn = document.getElementById('recheck-btn');
                const nextBtn = document.getElementById('next-btn');
                const checksTableDiv = document.getElementById('checks-table');

                function updateNextButtonStatus() {
                    const allOkInput = document.getElementById('all-checks-ok');
                    if (allOkInput && allOkInput.value === '1') {
                        nextBtn.classList.remove('disabled');
                        nextBtn.setAttribute('aria-disabled', 'false');
                    } else {
                        nextBtn.classList.add('disabled');
                        nextBtn.setAttribute('aria-disabled', 'true');
                    }
                }

                updateNextButtonStatus();

                recheckBtn.addEventListener('click', async function() {
                    recheckBtn.disabled = true;
                    recheckBtn.innerHTML = '<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> جاري الفحص...';

                    try {
                        const response = await fetch('installer/ajax.php?action=run_checks');
                        const data = await response.json();

                        if (data.status === 'success') {
                            checksTableDiv.innerHTML = data.html;
                            updateNextButtonStatus();
                        }
                    } catch (error) {
                        console.error('Re-check failed:', error);
                    } finally {
                        recheckBtn.disabled = false;
                        recheckBtn.innerHTML = 'إعادة الفحص';
                    }
                });

                nextBtn.addEventListener('click', function(e) {
                    if (nextBtn.classList.contains('disabled')) {
                        e.preventDefault();
                    }
                });
            }
        });
    </script>
</body>
</html>
