<?php
session_start();

// منع إعادة التثبيت إذا كان قد تم بالفعل
if (file_exists(__DIR__ . '/../install.lock')) {
    die("خطأ: المشروع تم تثبيته بالفعل. يرجى حذف ملف 'install.lock' يدوياً لإعادة التثبيت.");
}

// --- متغيرات التصميم ---
$styles = "
    body { font-family: sans-serif; background-color: #f4f4f9; color: #333; line-height: 1.6; }
    .container { max-width: 700px; margin: 50px auto; padding: 20px; background: #fff; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
    h1, h2 { color: #444; }
    table { width: 100%; border-collapse: collapse; margin-top: 20px; }
    th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
    th { background-color: #f8f8f8; }
    .status-ok { color: #28a745; font-weight: bold; }
    .status-error { color: #dc3545; font-weight: bold; }
    .btn { display: inline-block; padding: 10px 20px; margin-top: 20px; background-color: #007bff; color: #fff; text-decoration: none; border-radius: 5px; }
    .btn:hover { background-color: #0056b3; }
    .btn.disabled { background-color: #ccc; cursor: not-allowed; }
    .text-right { text-align: right; }
";

// --- منطق معالجة الفورم ---
$error = null;
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['form_step'])) {
    if ((int)$_POST['form_step'] === 2) {
        // معالجة فورم إنشاء حساب المدير
        $username = trim($_POST['username'] ?? '');
        $password = trim($_POST['password'] ?? '');

        if (strlen($username) > 2 && strlen($password) > 5) {
            $_SESSION['install_admin_user'] = [
                'username' => $username,
                'password_hash' => password_hash($password, PASSWORD_DEFAULT),
            ];
            header('Location: ?step=3');
            exit;
        } else {
            $error = "اسم المستخدم يجب أن يكون أطول من حرفين، وكلمة المرور أطول من 5 أحرف.";
        }
    } elseif ((int)$_POST['form_step'] === 3) {
        // --- إنشاء ملف الإعدادات ---
        $config_content = "<?php\n\n";
        $config_content .= "// Generated by installer on " . date('Y-m-d H:i:s') . " --\n\n";

        // Sanitize and prepare data
        $db_host = trim($_POST['db_host']);
        $db_user = trim($_POST['db_user']);
        $db_pass = trim($_POST['db_pass']);
        $db_name = trim($_POST['db_name']);

        $source_dirs = array_filter(array_map('trim', explode("\n", $_POST['source_dirs'])));
        $source_dirs_str = "['" . implode("', '", array_map('addslashes', $source_dirs)) . "']";

        $exclude_patterns = array_filter(array_map('trim', explode("\n", $_POST['exclude_patterns'])));
        $exclude_patterns_str = "['" . implode("', '", array_map('addslashes', $exclude_patterns)) . "']";

        $keep_days = (int)$_POST['keep_days'];
        $delete_old = isset($_POST['delete_old']) ? 'true' : 'false';

        $ftp_enabled = isset($_POST['ftp_enabled']) ? 'true' : 'false';
        $ftp_host = trim($_POST['ftp_host']);
        $ftp_user = trim($_POST['ftp_user']);
        $ftp_pass = trim($_POST['ftp_pass']);
        $ftp_dir = trim($_POST['ftp_dir']);

        // Build config content
        $config_content .= "// Database Settings\n";
        $config_content .= "define('DB_HOST', '" . addslashes($db_host) . "');\n";
        $config_content .= "define('DB_USER', '" . addslashes($db_user) . "');\n";
        $config_content .= "define('DB_PASS', '" . addslashes($db_pass) . "');\n";
        $config_content .= "define('DB_NAME', '" . addslashes($db_name) . "');\n\n";

        $config_content .= "// File Backup Settings\n";
        $config_content .= "define('SOURCE_DIRECTORIES', " . $source_dirs_str . ");\n";
        $config_content .= "define('EXCLUDE_PATTERNS', " . $exclude_patterns_str . ");\n\n";

        $config_content .= "// General Settings\n";
        $config_content .= "define('BACKUP_DIR', __DIR__ . '/../backups');\n";
        $config_content .= "define('LOG_FILE', __DIR__ . '/../logs/backup.log');\n";
        $config_content .= "define('DELETE_OLD_BACKUPS', " . $delete_old . ");\n";
        $config_content .= "define('KEEP_BACKUPS_FOR_DAYS', " . $keep_days . ");\n\n";

        $config_content .= "// FTP Settings\n";
        $config_content .= "define('FTP_ENABLED', " . $ftp_enabled . ");\n";
        $config_content .= "define('FTP_HOST', '" . addslashes($ftp_host) . "');\n";
        $config_content .= "define('FTP_USER', '" . addslashes($ftp_user) . "');\n";
        $config_content .= "define('FTP_PASS', '" . addslashes($ftp_pass) . "');\n";
        $config_content .= "define('FTP_DIR', '" . addslashes($ftp_dir) . "');\n";

        if (file_put_contents(__DIR__ . '/../config/config.php', $config_content)) {
            header('Location: ?step=4');
            exit;
        } else {
            $error = "فشل في كتابة ملف الإعدادات. يرجى التحقق من صلاحيات مجلد 'config'.";
            // Stay on step 3 to show the error
            $_GET['step'] = 3;
        }
    }
}


// --- منطق الخطوات ---
$step = isset($_GET['step']) ? (int)$_GET['step'] : 1;

function check_php_version() {
    return version_compare(PHP_VERSION, '7.2.0', '>=');
}

function check_extension($name) {
    return extension_loaded($name);
}

function check_writable($path) {
    return is_writable($path);
}

// --- عرض الواجهة ---
?>
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <title>معالج تثبيت سكربت النسخ الاحتياطي</title>
    <style><?php echo $styles; ?></style>
</head>
<body>
    <div class="container">
        <h1>معالج التثبيت</h1>

        <?php if ($step === 1): ?>
            <h2>الخطوة 1: التحقق من متطلبات السيرفر</h2>
            <?php
                $checks = [
                    'PHP Version (>= 7.2.0)' => check_php_version(),
                    'PDO SQLite Extension' => check_extension('pdo_sqlite'),
                    'Zip Extension' => check_extension('zip'),
                    'Config Directory Writable' => check_writable(__DIR__ . '/../config'),
                    'Backups Directory Writable' => check_writable(__DIR__ . '/../backups'),
                    'Logs Directory Writable' => check_writable(__DIR__ . '/../logs'),
                    'Database Directory Writable' => check_writable(__DIR__ . '/../database'),
                ];
                $all_ok = !in_array(false, $checks, true);
            ?>
            <table>
                <thead>
                    <tr>
                        <th>المتطلب</th>
                        <th>الحالة</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($checks as $label => $status): ?>
                    <tr>
                        <td><?php echo $label; ?></td>
                        <td>
                            <span class="status-<?php echo $status ? 'ok' : 'error'; ?>">
                                <?php echo $status ? 'متوفر' : 'غير متوفر أو لا يمكن الكتابة عليه'; ?>
                            </span>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>

            <div class="text-right">
                <?php if ($all_ok): ?>
                    <a href="?step=2" class="btn">الخطوة التالية &larr;</a>
                <?php else: ?>
                    <p class="status-error">يرجى إصلاح المشاكل المذكورة أعلاه ثم إعادة تحميل الصفحة.</p>
                    <a href="?step=1" class="btn disabled">الخطوة التالية &larr;</a>
                <?php endif; ?>
            </div>
        <?php endif; // End Step 1 ?>

        <?php if ($step === 2): ?>
            <h2>الخطوة 2: إنشاء حساب المدير</h2>
            <p>سيتم استخدام هذا الحساب لتسجيل الدخول إلى لوحة التحكم.</p>

            <?php if (isset($error)): ?>
                <p class="status-error"><?php echo $error; ?></p>
            <?php endif; ?>

            <form method="POST" action="?step=2">
                <input type="hidden" name="form_step" value="2">
                <table style="width:100%">
                    <tr>
                        <td style="width: 30%;"><label for="username">اسم المستخدم:</label></td>
                        <td><input type="text" id="username" name="username" required style="width: 95%; padding: 8px;"></td>
                    </tr>
                    <tr>
                        <td><label for="password">كلمة المرور:</label></td>
                        <td><input type="password" id="password" name="password" required style="width: 95%; padding: 8px;"></td>
                    </tr>
                </table>
                <div class="text-right">
                    <button type="submit" class="btn">الخطوة التالية &larr;</button>
                </div>
            </form>
        <?php endif; // End Step 2 ?>

        <?php if ($step === 3): ?>
            <h2>الخطوة 3: إعدادات النسخ الاحتياطي</h2>
            <p>الرجاء إدخال تفاصيل النسخ الاحتياطي المطلوبة.</p>
            <?php if (isset($error)): ?><p class="status-error"><?php echo $error; ?></p><?php endif; ?>

            <form method="POST" action="?step=3">
                <input type="hidden" name="form_step" value="3">

                <h3>إعدادات قاعدة البيانات (لـ `mysqldump`)</h3>
                <table>
                    <tr><td><label>مستضيف DB:</label></td><td><input type="text" name="db_host" value="localhost" class="input-field"></td></tr>
                    <tr><td><label>اسم مستخدم DB:</label></td><td><input type="text" name="db_user" value="root" class="input-field"></td></tr>
                    <tr><td><label>كلمة مرور DB:</label></td><td><input type="password" name="db_pass" class="input-field"></td></tr>
                    <tr><td><label>اسم قاعدة البيانات:</label></td><td><input type="text" name="db_name" required class="input-field"></td></tr>
                </table>

                <h3>إعدادات نسخ الملفات</h3>
                <table>
                    <tr>
                        <td><label>المجلدات المصدر (كل مجلد في سطر):</label></td>
                        <td><textarea name="source_dirs" rows="3" class="input-field" required>/var/www/html</textarea></td>
                    </tr>
                    <tr>
                        <td><label>ملفات/مجلدات للاستثناء (كل نمط في سطر):</label></td>
                        <td><textarea name="exclude_patterns" rows="4" class="input-field">node_modules
cache
*.log
*.tmp</textarea></td>
                    </tr>
                </table>

                <h3>إعدادات عامة</h3>
                <table>
                    <tr>
                        <td><label>حذف النسخ القديمة:</label></td>
                        <td><input type="checkbox" name="delete_old" value="1" checked></td>
                    </tr>
                    <tr>
                        <td><label>الاحتفاظ بالنسخ لمدة (أيام):</label></td>
                        <td><input type="number" name="keep_days" value="7" class="input-field"></td>
                    </tr>
                </table>

                <h3>إعدادات FTP (اختياري)</h3>
                <table>
                    <tr><td><label>تفعيل FTP:</label></td><td><input type="checkbox" name="ftp_enabled" value="1"></td></tr>
                    <tr><td><label>مستضيف FTP:</label></td><td><input type="text" name="ftp_host" class="input-field"></td></tr>
                    <tr><td><label>مستخدم FTP:</label></td><td><input type="text" name="ftp_user" class="input-field"></td></tr>
                    <tr><td><label>كلمة مرور FTP:</label></td><td><input type="password" name="ftp_pass" class="input-field"></td></tr>
                    <tr><td><label>مجلد FTP البعيد:</label></td><td><input type="text" name="ftp_dir" value="/backups" class="input-field"></td></tr>
                </table>
                <style>.input-field{width: 95%; padding: 8px;}</style>

                <div class="text-right">
                    <button type="submit" class="btn">حفظ وإنهاء التثبيت &larr;</button>
                </div>
            </form>
        <?php endif; // End Step 3 ?>

        <?php if ($step === 4): ?>
            <h2>الخطوة 4: إنهاء التثبيت</h2>
            <?php
                $install_success = false;
                try {
                    if (!isset($_SESSION['install_admin_user'])) {
                        throw new Exception("بيانات المدير غير موجودة في الجلسة. يرجى البدء من جديد.");
                    }

                    $db_path = __DIR__ . '/../database/users.db';
                    $pdo = new PDO('sqlite:' . $db_path);
                    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

                    $pdo->exec("CREATE TABLE IF NOT EXISTS users (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        username TEXT NOT NULL UNIQUE,
                        password_hash TEXT NOT NULL
                    )");

                    $stmt = $pdo->prepare("INSERT INTO users (username, password_hash) VALUES (?, ?)");
                    $stmt->execute([
                        $_SESSION['install_admin_user']['username'],
                        $_SESSION['install_admin_user']['password_hash']
                    ]);

                    touch(__DIR__ . '/../install.lock');
                    session_destroy();
                    $install_success = true;

                } catch (Exception $e) {
                    echo "<p class='status-error'>حدث خطأ فادح أثناء إنهاء التثبيت: " . $e->getMessage() . "</p>";
                }
            ?>

            <?php if ($install_success): ?>
                <p class="status-ok">تم التثبيت بنجاح!</p>
                <p>تم حذف بيانات التثبيت المؤقتة وتأمين النظام.</p>
                <p><strong>ملاحظة هامة:</strong> لأسباب أمنية، يرجى حذف ملف `public/install.php` الآن.</p>
                <div class="text-right">
                    <a href="index.php" class="btn">الذهاب إلى صفحة تسجيل الدخول &larr;</a>
                </div>
            <?php endif; ?>
        <?php endif; // End Step 4 ?>

    </div>
</body>
</html>
